\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename anubis.info
@settitle GNU Anubis Manual
@setchapternewpage odd
@finalout
@c %**end of header
@include version.texi
@include rendition.texi
@smallbook

@defcodeindex op
@defcodeindex cm
@syncodeindex fn cp

@copying
Copyright @copyright{} 2001, 2002, 2003, 2004 Wojciech Polak and Sergey Poznyakoff.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``A GNU Manual'',
and with the Back-Cover Texts as in (a) below.  A copy of the license
is included in the section entitled ``GNU Free Documentation License''.

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''
@end copying

@ifinfo
@dircategory Email
@direntry
* Anubis: (anubis).             The GNU outgoing mail processor.
@end direntry
@end ifinfo

@titlepage
@title GNU Anubis
@subtitle An outgoing mail processor and the SMTP tunnel
@subtitle GNU Anubis Version @value{VERSION}
@subtitle @value{UPDATED}
@author Wojciech Polak and Sergey Poznyakoff

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage


@node Top, Overview, , (dir)
@insertcopying
@ifinfo
@chapter GNU Anubis
This edition of the @cite{GNU Anubis Manual}, last updated @value{UPDATED},
documents GNU Anubis Version @value{VERSION}.
@end ifinfo

@menu
* Overview::                        Preliminary information.
* Glossary::                        Frequently Used Terms Explained.
* Authentication::                  How Incoming Connections Are Authenticated.
* Configuration::                   Writing your own configuration files.
* Rule System::                     How to use the Rule System.
* Invoking Anubis::                 How to invoke the GNU @command{anubis}.
* Sample Beginning::                Here is a sample beginning.
* TLS/SSL::                         Using the TLS/SSL Encryption.
* S/MIME::                          Using S/MIME signatures.
* Problems::                        Reporting bugs.

Appendices

* Pixie-Dixie::                     Original description of the new
                                    GNU Anubis operation mode.
* GNU Free Documentation License::  This manual is under the GNU Free
                                    Documentation License.
Indices

* Concept Index::                   Index of concepts.
@end menu


@node Overview, Glossary, Top, Top
@chapter Overview
@cindex overview
@cindex Simple Mail Transport Protocol, SMTP
@cindex daemon
@cindex client
@cindex tunnel
@cindex proxy
@cindex server
@cindex outgoing mail processor
@cindex on-the-fly
@cindex MUA, Mail User Agent
@cindex MTA, Mail Transport Agent

GNU Anubis is an outgoing mail processor. Its purpose is to receive
the outgoing message, perform some manipulations over its contents,
and to forward the altered message to the mail transport agent.

The usual mail sending scheme looks as follows: the user composes
his message using @dfn{mail user agent} (@dfn{MUA} for short). Once
the message is composed, the user sends it. When the MUA receives
the send command it connects to the @dfn{mail transport agent}
(@dfn{MTA} for short) and passes it the message for delivery. The
figure below illustrates this interaction:

@smallexample
+-------+                 +-------+               
|  MUA  | ---[outmsg]---> |  MTA  | ... [outmsg]
+-------+                 +-------+         |     
                                            |
                                            V
                                     +--------------+
                                     |  Recipient's |
                                     |   Mailbox    |  
                                     +--------------+
                                                        
@end smallexample

As shown in this figure, the outgoing message (@dfn{outmsg}), reaches
the recipient's mailbox unaltered.

However, there are situations where it may be necessary to modify
the outgoing message before it reaches MTA. As the simplest example,
the user might wish to sign the outgoing messages with his PGP
key, but his MUA does not support this operation or supports it
unconditionally.

In such cases, installing GNU Anubis between the MUA and MTA
allows the user to perform any additional processing on the
sent message. The figure below illustrates this concept:

@smallexample
+-------+                 +--------+                 +-------+               
|  MUA  | ---[outmsg]---> | Anubis | ---[modmsg]---> |  MTA  | 
+-------+                 +--------+                 +-------+     
                                                         |
                                                      [modmsg]
                                                         .
                                                         .
                                                         V
                                                  +--------------+
                                                  |  Recipient's |
                                                  |   Mailbox    |  
                                                  +--------------+
@end smallexample

The outgoing message is processed by GNU Anubis, and it is
the resulting message (@dfn{modmsg}) that reaches the MTA.

GNU Anubis is able to perform on messages a wide set of operations,
such as modifying message headers or body, encrypting or signing
messages with GPG (GNU Privacy Guard) keys, installing secure tunnels
to MTA using TLS/SSL encryption, tunneling messages through
SOCKS proxies, etc.

When the set of built-in operations is not enough, the user can
define his own operations using Guile, a @dfn{GNU's Ubiquitous
Intelligent Language for Extensions}.

The message processing is controlled by system-wide and per-user
configuration files written in a flexible and easy to use
command scripting language, specially designed for this
purpose.


@node Glossary, Authentication, Overview, Top
@chapter Glossary of Frequently Used Terms

@table @dfn
@item Authentication
A process whereby Anubis determines the authenticity of the connecting
party, its user name and configuration settings.

@item Protocol
Any standard for the exchange of information. A protocol
defines the specific wording and control flow for communications between
two or more programs, devices, or systems.

@item SMTP
Simple Mail Transport Protocol is a common mechanism for exchanging
mail across a network. This protocol is described in the RFC 821 document.

@item Daemon
We use a term @dfn{daemon} to define a process that runs in the
background, doing automated processing.

@item Server
A server provides information or other services for its
clients. Most network protocols are client--server based. This term usually
refers to an entire machine, but it can refer (and we're doing that) also
to the particular program or process, on that machine, that provides the
service.

@item Proxy
We use a term @dfn{proxy} to define a program, which goes
between the MUA and the MTA (it makes a tunnel). It can be used as a gateway
to the outside world, while using a firewall. In this case the host
under the firewall sends data to the proxy server, which in turn
forwards it to the real server outside, receives 
the response, and passes it back to the internal host.

@item Guile
GNU's Ubiquitous Intelligent Language for Extensions. It provides a
Scheme interpreter conforming to the R4RS language specification. GNU
Anubis uses Guile as its extension language.
For more information about Guile,
@xref{Top,,Overview,guile,The Guile Reference Manual}.

@item GPG
GNU Privacy Guard, a tool compatible with the Pretty Good Privacy.
@end table

@node Authentication, User Database, Glossary, Top
@chapter Authentication
@cindex authentication

@UNREVISED{}

When GNU Anubis accepts an incoming connection, it first has to identify
the remote party, i.e. determine whether it has the right to use
Anubis resources and, if so, what configuration settings should be
used during the session. We call this process @dfn{authentication}.
The exact method of authentication depends on Anubis @dfn{operation
mode}. Currently there are two modes:

@table @asis
@item transparent
This is the default mode. It is compatible with versions of GNU Anubis
up to 3.6.2. In this mode, Anubis relies on AUTH service (@command{identd})
to authenticate users.

@item auth
This mode uses SMTP AUTH mechanism to authenticate incoming
connections. @xref{Pixie-Dixie}, this is the first draft
description of this mode.
@end table

Both modes have their advantages and deficiencies, which you
have to weigh carefully before choosing which one to use. These
are discussed below:

@subheading Transparent (@samp{traditional}) mode.

Deficiencies:
@enumerate
@item The user must have @command{identd} installed on his machine.
@item Each user must have a system account on the machine where
GNU Anubis runs (though the system administrator may relax
this limitation using user name translation, @pxref{TRANSLATION
Section}).
@end enumerate

@noindent
Advantages:
@enumerate
@item Relative simplicity. You don't have to create your users database.
@item Authentication is performed immediately after the connection.
@end enumerate

@subheading Auth mode.

Deficiencies:
@enumerate
@item You have to maintain your users database
@item User's MUA must be able to perform ESMTP AUTH.@footnote{It is
not a serious restriction, however. The user may install Anubis on his
machine for the sole purpose of SMTP authentication, as Pixie-Dixie suggests.}
@end enumerate

@noindent
Advantages:
@enumerate
@item Better reliability.
@item Users do not have to run @command{identd} on their machines.
@item Users are not required to have accounts on the machine where
Anubis runs.
@item Users can remotely modify their configuration files.
@end enumerate

@menu
* User Database::
* Database URL::
* Managing the Database::
@end menu

@node User Database, Database URL, Authentication, Authentication
@section User Database
@UNREVISED{}

GNU Anubis uses @dfn{User Database} for keeping @dfn{user credentials},
i.e. data used to authenticate and authorize users. The exact way of
storing these data does not matter here, it will be addressed further
in this manual. In this section we treat user database as an
abstraction layer.

The user database consists of @dfn{records}. Each record keeps
information about a particular @dfn{user}. A record consists
of four @dfn{fields}. A field may contain some value, or be
empty, in which case we say that the field has @dfn{null}
value.

The record fields are:

@table @code
@item SMTP AUTHID
SMTP authentication ID of the user.

@item AUTH PASSWORD
SMTP password.

@item ACCOUNT
System user name to be used.

@item CONFIG
Path to the configuration file.
@end table

The first two fields are mandatory and must always have non-null values.
No two records in the database may have the same value of
@code{SMTP AUTHID} field. When @command{anubis} is trying to
authenticate a user, it first looks up in the database a record
with the value of @code{SMTP AUTHID} field matching AUTHID given
by the user. If no such entry is found, authentication fails.
Otherwise, @command{anubis} goes on and compares the password
supplied by the user with that from @code{AUTH PASSWORD} column.
If these match, authentication succeeds and @command{anubis}
passes to authorization state.

In this state, it first determines the user @acronym{ID}
(@acronym{UID}) to switch to. If the @code{ACCOUNT} field
is not null, its value is used as a login name of the system
account to use. If it is null, @command{anubis} switches to
the privilege level of a @dfn{default not privileged user},
specified by @code{user-notprivileged} statement in the global
configuration file (@pxref{Security Settings, user-notprivileged}).

The final step is to parse @dfn{user configuration file}. If
@code{CONFIG} field is not null, its value is used as absolute
path to the configuration file. Otherwise, @command{anubis} searches
for file @file{~/.anubisrc} (where @samp{~} denotes home directory
for the system account obtained on the previous step) and if such
a file exists, loads it.

@node Database URL, text, User Database, Authentication
@section Database URL
@UNREVISED{}

Anubis database is identified by its @dfn{URL}, or @dfn{Universal
Resource Locator}. A @code{URL} consists of following elements
(square brackets enclose optional elements):

@smallexample
@var{proto}://[[@var{user}[:@var{password}]@@]@var{host}]/@var{path}[@var{params}]
@end smallexample

The detailed description of each @code{URL} part follows:

@table @var
@item proto
Specifies a database @dfn{protocol}. The protocol describes how
the database is to be accessed. In a way, it may be regarded as
specifying the database @dfn{type}. Currently, GNU Anubis supports
following database protocols:

@multitable @columnfractions .20 .80
@item @samp{text} @tab A plain text file, containing users' credentials.
@item @samp{gdbm} @tab @acronym{GDBM} database
@item @samp{mysql} @tab @acronym{MySQL} database
@item @samp{pgsql} @tab @acronym{PostgreSQL} database
@item @samp{postgres} @tab Alias for @samp{pgsql}.
@end multitable

These protocols are described in detail below.

@item user
User name necessary to access the database. 

@item password
User password necessary to access the database. 

@item host
Domain name or IP address of a machine running the database.

@item path
A @dfn{path} to the database. The exact meaning of this element
depends on the database protocol. It is described in detail when
discussing particular database protocols.

@item params
A list of protocol-dependent parameters. Each parameter is of the
form @code{@var{keyword}=@var{name}}, parameters are separated
by semicolons.
@end table

@menu
* text::        Plain text databases
* gdbm::        Databases in GDBM format
* sql::         MySQL and PostgreSQL databases
@end menu

@node text, gdbm, Database URL, Database URL
@subsection Plain text databases
@UNREVISED{}

This is the simplest database possible. It is kept in a plain text
file. Each line in this file represents a single @dfn{record}, empty lines
and lines beginning with @samp{#} (@dfn{comments}) sign are ignored.
Records consist of @dfn{fields}, each field being a sequence of
non-whitespace characters. Fields are separated by arbitrary amount
of whitespace. A record may contain from two to four fields, whose
meaning is as follows:

@enumerate 1
@item SMTP @samp{AUTHID}.
@item SMTP password.
@item Account name. 
@item Path to user configuration file.
@end enumerate 

@subheading URL syntax

The @acronym{URL} syntax for this type of databases is quite simple:

@smallexample
text:@var{path}
@end smallexample

@noindent
where @var{path} specifies absolute file name of the database file.

@node gdbm, sql, text, Database URL
@subsection Databases in GDBM format
@UNREVISED{}

The protocol value @samp{gdbm} specifies a @dfn{GDBM database}. For
the detailed description of @acronym{GDBM} system
@ref{Top,,Introduction,gdbm,The GNU DBM Manual}.

@FIXME{Technically speaking, each @acronym{GDBM} record consists of
a @dfn{key} and @dfn{content}. Its @code{key} holds the value of
SMTP @samp{AUTHID}, whereas its @code{content} holds SMTP password,
system account name and path to user configuration file, separated by
commas. As usual, the two last fields are optional.

I doubt if this technical information would be of any use to the
reader.}

@acronym{URL} syntax for @acronym{GDBM} databases is: 

@smallexample
gdbm:@var{path}
@end smallexample

@noindent
where @var{path} specifies absolute file name of the database file.

@node sql, Managing the Database, gdbm, Database URL
@subsection MySQL and PostgreSQL
@UNREVISED{}

This is the most flexible database format. GNU Anubis @value{VERSION}
supports MySQL@footnote{See @url{http://www.mysql.com}.} and
PostgreSQL@footnote{See @url{http://www.postgres.org}.} interfaces.
No matter which of them you use, the implementation details are hidden
behind a single consistent Anubis interface.

GNU Anubis supposes that all user data are kept in a single database
table. This table must have at least four columns for storing
SMTP @samp{AUTHID}, SMTP password, system account name and path to
user configuration file. Among those, only the last two may have
NULL values. There is no restriction on the name of the database or
the authentication table, nor on its column names. This information
may be specified in @acronym{URL} as discussed below.

@subheading URL syntax

@smallexample
@var{proto}://[[@var{user}[:@var{password}]@@@var{host}/@var{dbname}[@var{params}]
@end smallexample

@var{Proto} describes the exact database type to use. Use @samp{mysql}
for MySQL databases and @samp{pgsql} or @samp{postgres} for PostgreSQL
databases.

Optional @var{user} and @var{password} specify authentication
credentials used to access the database. 

@var{Host} sets domain name or IP address of the machine running
the database. It may be omitted if the database resides on 
@samp{localhost}.

The database name is specified by @var{dbname} element.

Finally, further details needed for connecting to the database may
be given by @acronym{URL} parameters. All of them have reasonable
default values, so you'll have to specify only those parameters that
does not match the default values. Known parameters are:

@table @var
@item @var{port}=@var{number}
Specifies the port number to be used when connecting to the database.
If it is not specified, the behavior depends on the value of
@var{socket} parameter: if @var{socket} is not present, the program
will use the default port number for the given protocol (i.e. 3306
for @samp{mysql} and 5432 for @samp{pgsql}.

@item @var{socket}=@var{string}
Specifies UNIX name of the socket to connect to. This parameter cannot be
used together with @var{port} (see above).

@item @var{bufsize}=@var{number}
Sets the length of the buffer used to create SQL queries. Default is
1024 bytes.

@item @var{table}=@var{string}
Specifies the name of database table keeping where the authentication
data are stored. Default is @samp{users}.

@item @var{authid}=@var{string}
Specifies the name of a column in @var{table} which holds 
@samp{AUTHID} value. Default is @samp{authid}.

@item @var{passwd}=@var{string}
Specifies the name of a column in @var{table} which holds 
user password. Default is @samp{passwd}.

@item @var{account}=@var{string}
Specifies the name of a column in @var{table} which holds
the name of system account to be used for this @samp{AUTHID}. Default
is @samp{account}.

@item @var{rccol}=@var{string}
Specifies the name of a column in @var{table} which holds
path to the user's configuration file. Default is @samp{rccol}.

@FIXME{An example, please.}

@end table

@node Managing the Database, Administrators, sql, Authentication
@section Managing the Database
@UNREVISED{}

Managing the user database is a complex task, which looks differently
from administrator's and user's point of view. The administrator have
full rights on the database, it can add new records and delete or
modify existing ones. A user, of course, does not have such ample
rights. The only thing he is able to do is to maintain his own
record in the database, provided that he already has one. If he
does not, he should contact the system administrator and arrange
for the creation of his record.

@menu
* Administrators::      The Administrator's View
* Users::               The User's View
@end menu

@node Administrators, Create, Managing the Database, Managing the Database
@subsection Administrators
@UNREVISED{}

All administrative tasks are done using @command{anubisadm} command ---
a multipurpose tool for Anubis administrator.

The command usage syntax is:

@smallexample
anubisadm @var{command} [@var{options}] @var{database-url}
@end smallexample

@noindent
where @var{command} specifies the operation to be performed on the
database, @var{options} give additional operation-specific parameters,
and @var{database-url} specifies the database to operate upon.

All administrative tasks can be subdivided into the following
five categories:

@itemize
@item Creating the Database
@item Listing Database Records
@item Adding New Records
@item Removing Existing Records       
@item Modifying Existing Records
@end itemize

These operations are described in detail in the following
subsections@FIXME{Err, actually ``subsubsections'', but I don't like
the word}. 

@menu
* Create::              Creating the Database
* List::                Listing Database Records
* Add::                 Adding New Records
* Remove::              Removing Existing Records       
* Modify::              Modifying Existing Records
* anubisadm summary::   Summary of All Administrative Commands
@end menu

@node Create, List, Administrators, Administrators
@subsubsection Creating the Database

To create a database use @kbd{anubisadm --create} (or
@kbd{anubisadm -c}) command. @command{Anubisadm} will read database
entries from the standard input and write them to the database.
The standard input is supposed to be formatted as @code{text} database
(@pxref{text}).

Thus to create a @acronym{GDBM} database from plain text file
@file{userlist}, use the following command

@smallexample
anubisadm --create gdbm:/etc/anubis.db < userlist
@end smallexample

@noindent
Similarly, to create an initially empty database, type

@smallexample
anubisadm --create gdbm:/etc/anubis.db < /dev/null
@end smallexample

@emph{Notice}, that if you use @acronym{SQL} database format,
@option{--create} command does not imply creating the database
structure! So, before running

@smallexample
anubisadm --create mysql://localhost/dbname < userlist
@end smallexample 

@noindent
make sure you create the underlying database structure (including
granting privileges to the @command{anubis} user), via the
usual procedure. Please refer to corresponding database manual
for the detailed instructions on this.

It is sometimes necessary to convert the existing user database
from one format (protocol) to another. For example, suppose you
have been running @acronym{GDBM} database (@code{text:/etc/anubis.db})
for some time, but now it has grown considerably and you decided to
switch to PostgreSQL database to improve performance. To do so,
first create the database using postgres utilities. Then run

@smallexample
anubisadm --list text:/etc/anubis.db | \
 anubisadm --create pgsql://localhost/dbname
@end smallexample

@noindent 
That's all there is to it!

@node List, Add, Create, Administrators
@subsubsection Listing Database Records

The command @option{--list} (or @option{-l}) lists the existing
database. When run without additional options, it will display
all records from the database, e.g.:

@smallexample
anubisadm --list gdbm:/etc/anubis.db
@end smallexample

Among its other uses, such invocation is handy for converting
user database to another format (@pxref{Create}).

If you wish to list only a particular record, specify the 
@code{AUTHID} using @option{--authid} (@option{-i}) option. For example,
to list record of the user with @code{AUTHID} @samp{test},
type:

@smallexample
example$ anubisadm --list --authid test gdbm:/etc/anubis.db
@end smallexample


@node Add, Remove, List, Administrators
@subsubsection Adding New Records

To add a new record use command @option{--add} (@option{-a}).
Additional data are specified via the following options:

@table @option
@item -i @var{string}
@itemx --authid=@var{string}
Specify the user @code{SMTP AUTHID}. 

@item -p @var{string}
@itemx --password=@var{string}
Specify user password password. 

@item -u @var{string}
@itemx --user=@var{string}
Specify system user name corresponding to the given @code{AUTHID}.

@item -f @var{string}
@itemx --rcfile=@var{string}
Specify configuration file to be used for this user.
@end table

For example, the following command adds a record with @code{SMTP
AUTHID} @samp{test}, password @samp{guessme} and maps it
to the system account @samp{gray}:

@smallexample
anubisadm --add --authid test --password guessme \
          --user gray gdbm:/etc/anubis.db
@end smallexample

@node Remove, Modify, Add, Administrators
@subsubsection Removing Existing Records

Removing a record is quite straightforward: use @option{--remove}
(@option{-r}) command and specify @code{AUTHID} using
@option{--authid} option. For example, to remove the record created
in the previous subsection, run:

@smallexample
anubisadm --remove --authid test gdbm:/etc/anubis.db
@end smallexample

@node Modify, anubisadm summary, Remove, Administrators
@subsubsection Modifying Existing Records

To modify an existing record use command @option{--modify}
(@option{-m}). The record is identified via @option{--authid} option.
The fields to be changed are given with the following options:

@table @option
@item -p @var{string}
@itemx --password=@var{string}
Specify user password password. 

@item -u @var{string}
@itemx --user=@var{string}
Specify system user name corresponding to the given @code{AUTHID}.

@item -f @var{string}
@itemx --rcfile=@var{string}
Specify configuration file to be used for this user.
@end table

For example, the following command sets new configuration file name
for the user @samp{smith}:

@smallexample
anubisadm --authid smith \
          --rcfile=/var/spool/anubis/common gdbm:/etc/anubis.db
@end smallexample

@node anubisadm summary, Users, Modify, Administrators
@subsubsection Summary of All Administrative Commands

@subheading Usage
@smallexample
anubisadm @var{command} [@var{options}] @var{database-url}
@end smallexample

@noindent
@subheading Commands:
@table @option
@item -c
@itemx --create
Create the database.

@item -l
@item --list
List the contents of an existing database.

@item -a
@item --add
Add a new record.

@item -m
@itemx --modify
Modify an existing record.

@item -r
@item --remove
Remove an existing record.

@item --version
Display program version number and exit.

@item --help
Display short usage summary and exit.
@end table

@noindent
@subheading Options:
@table @option
@item -i @var{string}
@itemx --authid=@var{string}
Specify the authid to operate upon. This option is mandatory for
@option{--add}, @option{--modify} and @option{--remove} commands.
It may also be used with @option{--list} command.

@item -p @var{string}
@itemx --password=@var{string}
Specify the password for the authid. This option is mandatory for
@option{--add}, @option{--modify} and @option{--remove} commands.

@item -u @var{string}
@itemx --user=@var{string}
Specify the system user name corresponding to the given authid. It may
be used with @option{--add}, @option{--modify}, and @option{--remove}
commands.

@item -f @var{string}
@itemx --rcfile=@var{string}
Specify the rc file to be used for this authid. The option may
be used with @option{--add}, @option{--modify}, and @option{--remove}
commands.
@end table

@node Users, Configuration, anubisadm summary, Managing the Database
@subsection Users
@UNREVISED{}

Users maintain their database records using @command{anubisusr}
command. Main purpose of this command is to keep the copy of
your configuration on GNU Anubis server up to date.
@FIXME{anubisusr should also allow to modify user
password. This is the only database field, apart from @code{CONFIG}
that the user may be allowed to change}. We recommend to invoke
@command{anubisusr} from your @file{~/.profile}, which will make
sure that your configuration file is up to date when you log in.
@footnote{Make sure to run @command{anubisusr} in background, so
it does not slow down your normal login sequence}.

@subheading Usage

@smallexample
anubisusr [@var{options}] [@var{smtp-url}]
@end smallexample

@noindent
where @var{smtp-url} is a @acronym{URL} of your GNU Anubis server.
Notice that if it lacks user name and password, then
@command{anubisusr} will first try to retrieve them from your
@file{~/.netrc} file (See @cite{netrc(5)} for more info), and if not
found it will prompt you to supply them.

@subheading Options

@table @option
@item -m @var{mech}
@itemx --mechanism @var{mech}
Only use SASL mechanism @var{mech}. Use this option several times
to set a list of allowed mechanisms.

@item -v
@itemx --verbose
Verbose output. Multiple options increase the verbosity. Maximum verbosity
level is 3.

@item --version
Display program version number and exit.

@item --help
Display short usage summary and exit.
@end table

@node Configuration, Rule System, Users, Top
@chapter Configuration
@cindex configuration
@cindex settings
@cindex system configuration file
@cindex user configuration file

The behavior of GNU Anubis is controlled by two configuration files.
The @dfn{system configuration file}, @file{/etc/anubisrc},
specifies system-wide options that affect all users. This file is usually
owned by root. The @dfn{user configuration file} specifies what GNU
Anubis should do for a particular user. By default it is located
in @file{~/.anubisrc}. This location can be changed in auth mode.
To protect your passwords in the configuration files, use the 0600
(u=rw,g=,o=) permissions, otherwise GNU Anubis won't accept them.

@subheading Lexical Structure

Both configuration files use simple line-oriented syntax. Each
line introduces a single statement. A statement consists of
@dfn{words}, each word being defined as a contiguous sequence of
non-whitespace symbols. A word may be composed of alphanumeric
characters and any of the following punctuation symbols:
@samp{_}, @samp{.}, @samp{/}, @samp{-}. Any arbitrary sequence
of characters enclosed in a pair of double quotes is also recognized
as a word.

The familiar shell @dfn{here document} syntax may be used to produce
a word containing several lines of text. The syntax is:

@smallexample
<<[-]delimiter
    text
delimiter
@end smallexample                                                  

If ``here document'' starts with @samp{<<-}, then all leading tab
characters are stripped from input lines and the line containing
@dfn{delimiter}. This allows to indent here-document in a natural
fashion.

To summarize all the above, let's consider the example:

@smallexample
@group
first-word "second word" <<-EOT
                            Third word
                            containing several
                            lines of text
                            EOT
@end group
@end smallexample

@noindent
This line contains three words: @samp{first-word}, @samp{second word}
and the third one composed of the three lines between the @samp{EOT}
markers.

If a statement is very long, it may be split among several lines
of text. To do so, precede the newline characters with a backslash
@samp{\}, e.g.:

@smallexample
@group
a very long statement\
  occupying several lines\
  of text
@end group  
@end smallexample

A @samp{#} in a line starts a @dfn{comment}. It and the rest of
the line are ignored. Comments may appear on any of the lines in
the configuration file, except on a commands and within a
``here-document'' construction.
A line containing just a comment (with perhaps spaces before it) is
effectively blank, and is ignored. For example:

@smallexample
@group
# This is a comment
if header[Subject] :re "No.*"  # This is also a comment
  guile-process action-name This # is not a comment!!!
fi
@end group
@end smallexample

@subheading Logical Structure

The statements within a configuration file are grouped into
@dfn{sections}. Each section has its name. A section begins with
one of the following constructs:

@smallexample
BEGIN @var{name}
---BEGIN @var{name}---
@end smallexample

@noindent

and ends with one of the following constructs:

@smallexample
END
---END---
@end smallexample

Notice, that both @samp{BEGIN} and @samp{END} must be uppercase.
When using the second form, any amount of whitespace is allowed
between the three dashes and the word.

The sections cannot be nested.

There are five predefined sections, whose names are uppercase.
The user may define his own sections, which may then be referred
to from the @code{RULE} section as subroutines (@pxref{Call Action}).

The predefined section names are:

@table @dfn
@item AUTH
Controls authentication mechanisms. 
@item CONTROL
This section specifies the basic GNU Anubis behavior. Its presence
is required in the system configuration file. It may be used in
the user configuration file to override the system-wide settings.
@item TRANSLATION
This section specifies a translation map for remapping
remote or local users. It may be used only in the system-wide
configuration file.
@item GUILE
Contains the settings of the Guile interpreter. The section is
allowed in both configuration files.
@item RULE
Defines the rules that are used to alter the contents of the
messages (conditional and unconditional rules).
@end table

@menu
* AUTH Section::
* CONTROL Section::
* TRANSLATION Section::
* GUILE Section::
@end menu

@node AUTH Section, CONTROL Section, Configuration, Configuration
@section AUTH Section
@cindex AUTH section

@code{AUTH} session controls various aspects of authentication mode.

@deffn Option smtp-greeting-message @var{text}
@opindex smtp-greeting-message @var{text}
Configures the greeting message issued by GNU Anubis upon accepting
the connection.
@end deffn

@deffn Option smtp-help-message @var{help-text}
@opindex smtp-help-message @var{help-text}
Sets the test of the message issued by Anubis in response to SMTP
@code{HELP} command. @var{Help-text} is a list of strings. Each string
from the list will be displayed at a separate response line.
@end deffn

@deffn Option sasl-password-db @var{url}
@opindex sasl-password-db @var{url}
Sets the user database @acronym{URL} (@pxref{User Database}).
@end deffn

@deffn Option sasl-allowed-mech @var{mech-list}
@opindex sasl-allowed-mech @var{mech-list}
Defines the list of allowed authentication methods.
@end deffn

@node CONTROL Section, TRANSLATION Section, AUTH Section, Configuration
@section CONTROL Section
@cindex CONTROL section

The @samp{CONTROL} section specifies the basic GNU Anubis behavior.
Specified in the system configuration file, it applies to all users on
the machine, but each user can specify its own @samp{CONTROL} section,
to customize own settings. Of course, not all options can be set
or change by user. Some options can only be set in the system configuration
file, and some only in user configuration file. By default, options
specified in user configuration file have a @strong{higher} priority
that those specified in system configuration file.

All option names are case insensitive, so you can use
for instance: @code{bind} or @code{BIND} or @code{BiNd}, and so on.

@menu
* Basic Settings::
* Output Settings::
* Proxy Settings::
* Encryption Settings::
* Security Settings::
@end menu


@node Basic Settings, Output Settings, CONTROL Section, CONTROL Section
@subsection Basic Settings

@deffn Option bind [@var{host}:]@var{port}
@opindex bind [@var{host}:]@var{port}
Specify the TCP port on which GNU Anubis listens for connections.
The default @var{host} value is @w{@samp{INADDR_ANY}}, which means
that anyone can connect to GNU Anubis. The default @var{port} number
is 24 (private mail system). This option is available only in the
system configuration file. If you would like, for instance, to bind
GNU Anubis to port 25 (SMTP) and limit its clients only to those from
@samp{localhost}, then set the following in your system
configuration file:

@smallexample
bind localhost:25
@end smallexample
@end deffn

@deffn Option remote-mta @var{host}[:@var{port}]
@opindex remote-mta @var{host}[:@var{port}]
Specify a remote SMTP host name or IP address, which GNU Anubis will
connect and forward mail to (after a processing). The default @var{port}
number is 25. This option is available in both configuration files.
@end deffn

@deffn Option local-mta @var{file-name} [@var{args}]
@opindex local-mta @var{file-name} [@var{args}]
Execute a local SMTP server, which works on standard input and output
(inetd-type program). This option excludes the @samp{remote-mta} keyword
(or @samp{--remote-mta} command line option). For example:

@smallexample
local-mta /usr/sbin/sendmail -bs
@end smallexample
@end deffn

@deffn Option esmtp-auth @var{username}:@var{password}
@opindex esmtp-auth @var{username}:@var{password}
This option allows you to specify a user name and a password for the
ESMTP authentication. Use this option if your MTA requires such an
authentication, but your MUA does not support it. A @var{username}
and a @var{password} are separated with a colon (@samp{:}).
Currently only @dfn{CRAM-MD5} and @dfn{LOGIN} authentication methods are
supported (and @dfn{CRAM-MD5} has a priority). The @dfn{LOGIN} method,
for security reasons, can only be used both with the TLS/SSL encryption.
@end deffn

@deffn Option mode @var{mode-name}
@opindex mode @var{mode-name}

Selects Anubis operation mode. Allowed values for @var{mode-name}
are:

@table @asis
@item transparent
@item auth
@end table

@xref{Authentication}, for the detailed discussion of GNU Anubis
operation modes.
@end deffn

@node Output Settings, Proxy Settings, Basic Settings, CONTROL Section
@subsection Output Settings

@deffn Option termlevel @var{level}
@opindex termlevel @var{level}
This is a logging level for @code{syslogd} or a terminal (if using the
@samp{--foreground} command line option).  @var{level} can be one
of the following:

@table @asis
@item normal
Only errors are logged. This is the default level.

@item verbose
Produce more diagnostic output.

@item debug
Produce debugging output.

@item silent
Do not log anything.

@end table

This command may be used only in system configuration file.
@end deffn

@deffn Option logfile @var{file-name}
@opindex logfile @var{file-name}
This command specifies an additional file, where GNU Anubis can log its
information, but only those information available for a client. Only in
user configuration file. For example:

@smallexample
logfile "anubis.log"
@end smallexample

This will log to the @file{~/anubis.log} file in a client's home directory.
@end deffn

@deffn Option loglevel @var{level}
@opindex loglevel @var{level}
This option specifies an output level for an additional file
(@samp{logfile}). It can be used only in user configuration file.
@var{level} is one of the following:

@table @asis
@item none
@item fails
@item all
@end table
@end deffn

@deffn Option tracefile @var{yes-or-no}
@deffnx Option tracefile @var{file-name}
@opindex tracefile @var{yes-or-no}
@opindex tracefile @var{file-name}
This option instructs @command{anubis} to log the execution of
tests and actions from the RULE sections. This is useful
for debugging the configuration files.

When this option is used in the system-wide configuration file,
only its first form is allowed. Using @samp{tracefile yes} enables
logging of the actions and tests to the default syslog channel.
Using @samp{tracefile no} disables it.

When used in the user configuration file, a filename is allowed
as an argument to this option. This allows you to explicitly
specify to which file the tracing output should go. Otherwise,
using @samp{tracefile yes} enables logging to the same file
as @samp{logfile} (if possible).
@end deffn


@node Proxy Settings, Encryption Settings, Output Settings, CONTROL Section
@subsection Proxy Settings
@cindex SOCKS proxy

@deffn Option socks-proxy @var{host}[:@var{port}]
@opindex socks-proxy @var{host}[:@var{port}]
This option enables tunneling the connections through a SOCKS proxy server,
specified as an argument @var{host}. The @var{port} default value is
1080, which is a common port number for SOCKS proxies.
@end deffn

@deffn Option socks-v4 @var{yes-or-no}
@opindex socks-v4 @var{yes-or-no}
This specifies a SOCKS protocol version 4. By default it is turned off,
and a default mode is SOCKS protocol version 5.
@end deffn

@deffn Option socks-auth @var{username}:@var{password}
@opindex socks-auth @var{username}:@var{password}
Specify a user name and a password, if a SOCKS proxy server requires them.
A @var{username} and a @var{password} are separated with a colon (@samp{:}).
@end deffn


@node Encryption Settings, Security Settings, Proxy Settings, CONTROL Section
@subsection Encryption Settings

@deffn Option ssl @var{yes-or-no}
@opindex ssl @var{yes-or-no}
This option enables the TLS/SSL encryption between the MUA and the MTA.
Value @samp{no} is the default, but using the TLS/SSL encryption
is recommended. You should also specify a private key and a certificate
using the @samp{ssl-key} and @samp{ssl-cert} keywords (defined below).
@xref{TLS/SSL}, for details.
@end deffn

@deffn Option ssl-oneway @var{yes-or-no}
@opindex ssl-oneway @var{yes-or-no}
This option enables the @dfn{ONEWAY} encryption. Use this mode,
when you want to use the TLS/SSL, but your MUA doesn't provide
a support for ESMTP TLS/SSL. Using this option doesn't require
using the @samp{ssl-key} and @samp{ssl-cert} keywords.
@end deffn

@deffn Option ssl-cert @var{file-name}
@opindex ssl-cert @var{file-name}
Specify a certificate for the TLS/SSL encryption.
Value @file{anubis.pem} is the default.
@end deffn

@deffn Option ssl-key @var{file-name}
@opindex ssl-key @var{file-name}
Specify a private key for the TLS/SSL encryption.
Value @file{anubis.pem} is the default.
@end deffn

@deffn Option ssl-cafile @var{file-name}
@opindex ssl-cafile @var{file-name}
Specify a CA certificate file (supported only by GnuTLS).
@end deffn


@node Security Settings, , Encryption Settings, CONTROL Section
@subsection Security Settings

The following options control various security settings. 

@deffn Option allow-local-mta @var{yes-or-no}
@opindex allow-local-mta @var{yes-or-no}
For security reasons, this option is set to @samp{no}, but the @samp{yes}
value enables the @samp{local-mta} keyword (or @samp{--local-mta}
command line option), so if you want to use a local mail server,
which works on standard input and output, a supervisor must set
this option to @samp{yes}. The option is available only in system
configuration file.
@end deffn

@deffn Option drop-unknown-user @var{yes-or-no}
@opindex drop-unknown-user @var{yes-or-no}
This option drops an unknown user, i.e. a client which has not
been verified by IDENT service. Value @samp{no} is the default.
@end deffn

@deffn Option user-notprivileged @var{username}
@opindex user-notprivileged @var{username}
For security reasons, it is recommended to create an unprivileged user,
which the server runs as most of the time, when doing unprivileged
operations. The option is available only in system
configuration file. For example: 

@smallexample
user-notprivileged "anubis.unprivileged"
@end smallexample

@strong{Caution:} Create a user account named @w{@samp{anubis.unprivileged}}
in the @file{/etc/passwd}, if necessary. Add this user name also to the
@w{@file{/etc/anubis.allow}}, if using GNU Anubis with PAM support.
@end deffn

@deffn Option rule-priority @var{value}
@opindex rule-priority @var{value}

This statement defines the order of execution of the system and user
@code{RULE} sections (@xref{Rule System}, for detailed description).
It is available only in system configuration file.

@table @code
@item system
The system section is executed first, then the user section is executed.

@item user
The user section is executed first, next the system section is executed.

@item system-only
Only the system @code{RULE} section is executed.

@item user-only
Only the user @code{RULE} section is executed.
@end table
@end deffn

@deffn Option control-priority @var{value}
@opindex control-priority @var{value}

Sets the order of processing the @code{CONTROL} sections. The option is
available only in system configuration file. Its possible values are:

@table @code
@item system
The system @code{CONTROL} section is processed first. Notice, that
this means that the user may override the system settings in his
configuration file. This is the default setting.

@item user
The user @code{CONTROL} section is processed first. Thus, the
system-wide settings always override the user private settings.
@end table
@end deffn

@node TRANSLATION Section, GUILE Section, CONTROL Section, Configuration
@section TRANSLATION Section
@cindex TRANSLATION section

The @samp{TRANSLATION} section specifies how to translate remote or local
user names, or host names or addresses, to local user names.
The @samp{TRANSLATION} section is available @emph{only} in the system
configuration file. Syntax:

@smallexample
@group
---BEGIN TRANSLATION---
translate  [@var{user}@@]@var{address} into  @var{username}
...
---END---
@end group
@end smallexample

@var{address} means host name or IP address. You can also specify
@samp{0.0.0.0}, and it means any address (@samp{INADDR_ANY}).

An example:

@smallexample
@group
---BEGIN TRANSLATION---
translate jack@@somewhere.net into john
---END---
@end group
@end smallexample

@noindent
The rule above will allow a remote user @samp{jack} at @samp{somewhere.net}
to use the configuration file of the local user @samp{john}. Or you can write:
@w{@samp{translate somewhere.net into john}},
and this means that @emph{all} users at @samp{somewhere.net} are allowed to use
the local john's configuration file.


@node GUILE Section, , TRANSLATION Section, Configuration
@section GUILE Section
@cindex GUILE section
@cindex Guile
@cindex extension language
@cindex Scheme

@deffn Command guile-output @var{file}
Specifies the name of the file to bind to the Scheme standard error
and output ports. This option has no effect if GNU Anubis is started
with either of @option{--foreground} or @option{--stdio} command line
options. 
@end deffn

@deffn Command guile-debug @var{yes-or-no}
When set to @samp{yes} enables Guile stack traces and debugging output.
@end deffn

@deffn Command guile-load-path-append @var{path}
Appends the given @var{path} to the list of Guile load paths
(@pxref{Build Config, %load-path,,guile,The Guile Reference Manual}).
@end deffn

@deffn Command guile-load-program @var{file}
Reads the given Scheme program.
@end deffn


@node Rule System, Invoking Anubis, Configuration, Top
@chapter The Rule System
@cindex rule system

The rule system is a core part of GNU Anubis. It can be regarded
as a program that is executed for every outgoing message. 

Throughout this chapter, when showing syntax definitions, the
optional parts of these will be enclosed in a pair of square
brackets, e.g.:

@smallexample
keyword [@var{optional-part}] @var{mandatory-part}
@end smallexample

@noindent
When the square braces are required symbols, they will be marked
as such, e.g.:

@smallexample
remove @samp{[}@var{key}@samp{]}
@end smallexample

The rule system is defined in @dfn{RULE} section.
The statements within this section are executed sequentially.
Each statement is either an @dfn{action} or a @dfn{conditional
statement}.

@menu
* Actions::
* Conditional Statements::
* Triggers::
* Boolean Operators::
* Regular Expressions::
* Action List::
* Using Guile Actions::
@end menu


@node Actions, Conditional Statements, Rule System, Rule System
@section Actions
@cindex actions defined

An @dfn{action} is a statement defining an operation to be performed
over the message. Syntactically, each action is

@smallexample
@var{command} [=] @var{right-hand-side}
@end smallexample

@noindent
Where @var{command} specifies a particular operation and
@var{right-hand-side} specifies the arguments for it. The equal sign
is optional.


@node Conditional Statements, Triggers, Actions, Rule System
@section Conditional Statements
@cindex Conditional statements
@cindex @code{if}, conditional statements
@cindex @code{else}, conditional statements
@cindex @code{fi}, conditional statements

A @dfn{conditional statement} defines the control flow in the section.
It allows to execute arbitrary actions depending on whether a certain
condition is met. A conditional statement in its simplest form is:

@smallexample
if @var{part} [@var{pattern-match-flags}] @var{cond-expr}
  @var{action-list-1}
fi
@end smallexample
    
The @var{part} specifies which part of the input should be considered
when evaluating the condition. It is either @samp{command}, meaning
the text of an smtp command issued while sending the message, or
@samp{header}, meaning the value of an RFC822 header. Either of the
two may be followed by the name of the corresponding command or
header enclosed in square brackets. If this part is missing, all
command or headers will be searched. 

The optional @var{pattern-match-flags} alter the pattern matching
type used in subsequent conditional expression. It
will be described in detail in the section @ref{Regular Expressions}.
The @var{cond-expr} is a @dfn{conditional expression}.
It consists of a series of @dfn{conditions} joined together with
boolean operators @samp{and} or @samp{or} (@pxref{Boolean Operators}).
Each condition is:

@table @asis
@item = @var{regexp}
Returns true if the requested part of the input matches the given regular
expression (@var{regexp}).

@item != @var{regexp}
Returns true if the requested part of the input does not match the given
regular expression.

@item not @var{condition}
Reverses the sense of @var{condition}

@item ( @var{cond-expr} )
Returns the result of the conditional expression in parentheses. This
is useful for changing operator precedence. 
@end table

The simplest example:

@smallexample
@group
if header [Subject] "^ *Re:"
  ...
fi
@end group
@end smallexample

The actions represented by @dots{} will be executed only if the
@samp{Subject:} header of the message starts with @samp{Re:} optionally
preceded by any amount of whitespace.

The more elaborate form of a conditional allows you to choose among
the two different action sets depending on a given condition. The
syntax is:

@smallexample
if @var{part} [@var{flags}] @var{cond-expr}
  @var{action-list-1}
else
  @var{action-list-2}
fi
@end smallexample

Here, the @var{action-list-1} is executed if the condition
@var{cond-expr} is met. Otherwise, @var{action-list-2} is
executed.

@smallexample
@group
if @var{part} [@var{flags}] @var{cond-expr}
  @var{action-list-1}
else
  @var{action-list-2}  
fi
@end group
@end smallexample

@noindent
Note also, that in the examples above any of the statements
@var{action-list} may contain conditionals, so that the conditional
statements may be nested. This allows to create very sophisticated
rule sets. As an example, consider the following statement:

@smallexample
if [List-Id] :re ".*<anubis-commit@@gnu.org>"
  modify [Subject] "[Anubis Commit Notice] &"
else
  if [List-Id] :re ".*<bug-anubis@@gnu.org>"
    modify [Subject] "[Anubis Bug Notice] &"
  else
    add [X-Passed] "Subject checking"
  fi
fi  
@end smallexample

This statement, depending on the value of @code{List-Id} header, will
prepend the @code{Subject} header with an identification string, or add
an @code{X-Passed} header if no known @code{List-Id} was found.

@node Triggers, Boolean Operators, Conditional Statements, Rule System
@section Triggers
@cindex Triggers

Triggers are conditional statements that use the value of the
@samp{Subject} header to alter the control flow. Syntactically, a
trigger is:

@smallexample
@group
trigger [@var{flags}] @var{pattern}
  @var{action-list}
done
@end group
@end smallexample

@noindent
Here, @var{pattern} is the pattern against which the @samp{Subject}
header is checked, @var{flags} are optional flags controlling the
type of regular expression used (@pxref{Regular Expressions}). For
backward compatibility, the keyword @code{rule} may be used instead
of @code{trigger}.

The triggers act as follows: First, the value of the @samp{Subject} header is
matched against the pattern @samp{@@@@}@var{pattern}. If it matches,
then the matched part is removed from the @samp{Subject}, and the
@var{action-list} is executed.

Basically, putting aside the possibility to use different flavors of
regular expressions, a trigger is equivalent to the following statement:

@smallexample
@group
if header[Subject] :posix "(.*)@@@@@var{pattern}"
  modify header [Subject] "\1"
  @var{action-list}
fi
@end group
@end smallexample

Thus, adding the @samp{@@@@@var{rule-name}} code to the @samp{Subject}
header of your message, triggers a rule named @var{rule-name},
specified in a user configuration file. For example:

@smallexample
@group
---BEGIN RULE---
trigger :basic "^gpg-encrypt-john"
   gpg-encrypt "john's_gpg_key"
done
---END---
@end group
@end smallexample

@noindent
Now you can simply send an email with the following subject:
@w{@samp{hello John!@@@@gpg-encrypt-john}} to process an outgoing message
with the rule specified above---encrypt message with a John's public key.
Moreover, the trigger will remove the @samp{@@@@}, so John will only receive
a message with a subject @samp{hello John!}.

Another example shows an even more dynamic trigger, that is using
a substitution and back-references:

@smallexample
@group
---BEGIN RULE---
trigger :extended "^gpg-encrypt:(.*)"
   gpg-encrypt "\1"
   add [X-GPG-Comment] "Encrypted for \1"
done
---END---
@end group
@end smallexample

@noindent
To encrypt a message to user e.g. @samp{John}, simply send an email with
a subject @w{@samp{hello John!@@@@gpg-encrypt:john's_gpg_key}}.
This way, you decide at a run time which public key should be used,
without creating separate rules for each user; thanks to back-references,
those 3---4 lines are enough.


@node Boolean Operators, Regular Expressions, Triggers, Rule System
@section Boolean Operators

The following table lists the three boolean operators that can be used
in Anubis conditional expressions in the order of increasing binding
strength:

@itemize @bullet
@item @samp{OR}
@item @samp{AND}
@item @samp{NOT}
@end itemize

As an example, let's consider the following statement:

@smallexample
@group
if header[X-Mailer] "mutt" or header[X-Mailer] "mail" \
   and not header[Content-Type] "^multipart/mixed;.*"
   @var{action}
fi
@end group
@end smallexample
@noindent

In this case the @var{action} will be executed if the @code{X-Mailer}
header contains the word @samp{mutt}. The same @var{action} will also
be executed if the @code{X-Mailer} header contains the word @samp{mail}
@emph{and} the value of the @code{Content-Type} header does not begin
with the string @samp{multipart/mixed}.

Now, if we wished to execute the @var{action} for any message sent
using @command{mail} or @command{mutt} whose @code{Content-Type}
header does not begin with the string @samp{multipart/mixed}, we would
write the following:

@smallexample
@group
if (header[X-Mailer] "mutt" or header[X-Mailer] "mail") \
   and not header[Content-Type] "^multipart/mixed;.*"
   @var{action}
fi
@end group
@end smallexample
@noindent

Notice the use of parentheses to change the binding strength of the
boolean operators.


@node Regular Expressions, Action List, Boolean Operators, Rule System
@section Regular Expressions
@cindex regex, flag
@cindex re, flag
@cindex perl, flag
@cindex perlre, flag
@cindex exact, flag
@cindex ex, flag
@cindex scase, flag
@cindex icase, flag
@cindex basic, flag
@cindex extended, flag

GNU Anubis supports two types of regular expressions: POSIX (both
basic and extended), and Perl-style regular expressions. Among this,
the former are always supported, whereas the support for the latter
depends on the configuration settings at compile time. The default
type of regular expressions is POSIX Extended. 

A number of modifiers is provided to change the type of regular
expressions. These are described in the following table.

@table @code
@item :regex
@itemx :re
Indicates that the following pattern should be considered a regular
expression. The default type for this expression is assumed.

@item :perl
@itemx :perlre
The regular expression is a Perl-style one.

@item :exact
@itemx :ex
Disables regular expression matching, all patterns will be matched
as exact strings.

@item :scase
Enables case-sensitive comparison.

@item :icase
Enables case-insensitive comparison.

@item :basic
Switches to the POSIX Basic regular expression matching.

@item :extended
Switches to the POSIX Extended regular expression matching.
@end table

The special statement @code{regex} allows you to alter the default
regular expression type. For example, the following statement

@smallexample
regex :perl :scase
@end smallexample

sets the default regular expression types to Perl-style, case-sensitive.
The settings of @code{regex} statement regard only those patterns that
appear after it in the configuration file and have force until the
next occurrence of the @code{regex} statement. 

A couple of examples:

@smallexample
@group
if header[Subject] :perlre "(?<=(?<!foo)bar)baz"
 ...
fi
@end group
@end smallexample

@noindent
This will match any @code{Subject} header whose value
matches an occurrence of @samp{baz} that is preceded by @samp{bar}
which in turn is not preceded by @samp{foo}.
              
@smallexample
if header[Subject] :scase "^Re"
@end smallexample

@noindent
will match a @code{Subject} header whose value starts with @samp{Re},
but will not match it if it starts with @samp{RE} or @samp{re}.

When using POSIX regular expressions, the extended syntax is enabled
by default. If you wish to use a basic regular expression, precede
it with the @code{:basic} flag.

For the detailed description of POSIX regular expressions,
@xref{Top,,Regular Expression Library,regex,Regular Expression Library}.
For information about Perl-style regular expressions, refer to the
Perl documentation.


@node Action List, Using Guile Actions, Regular Expressions, Rule System
@section Action List
@cindex Action List

An @dfn{action list} is a list of action commands, which control processing
of an outgoing messages. All action command names are case insensitive, so you
can use for instance: @samp{add} or @samp{ADD} or @samp{AdD}, and so on.

@menu
* Stop Action::            Stopping the Processing
* Call Action::            Invoking Another Section
* Adding Headers or Text:: How to add a new header or body line(s).
* Removing Headers::       How to remove a message header line(s).
* Modifying Messages::     How to modify a message contents on-the-fly.
* Inserting Files::        How to append text files to an outgoing message.
* Mail Encryption::        How to encrypt a message on-the-fly.
* External Processor::     How to process a message body using an external tool.
* Quick Example::          A quick example of using an action list.
@end menu


@node Stop Action, Call Action, Action List, Action List
@subsection Stop Action
@cindex @code{stop}

The @code{stop} command stops immediately the processing of the
section. It may be used in the main @code{RULE} section as well as
in any user-defined section. For example:

@smallexample
if not header[Content-Type] "text/plain; .*"
  stop;
fi
@end smallexample


@node Call Action, Adding Headers or Text, Stop Action, Action List
@subsection Call Action
@cindex @code{call}

The @code{call} command allows to invoke a user-defined section much
in the same manner as a subroutine in a programming language. The
invoked section continues to execute until its end or the @code{stop}
statement is encountered, whichever the first.

@smallexample
BEGIN myproc
if header[Subject] "Re: .*"
  stop;
fi
trigger "pgp"
  gpg-encrypt "my_gpg_key"
done
END

BEGIN RULE
call myproc
END
@end smallexample


@node Adding Headers or Text, Removing Headers, Call Action, Action List
@subsection Adding Headers or Text
@cindex @code{add}

The @code{add} command allows you to add arbitrary headers or text
to the message. To add a header, use the following syntax:

@deffn Command add header @samp{[}@var{name}@samp{]} @var{string}
@deffnx Command add @samp{[}@var{name}@samp{]} @var{string}
For example:

@smallexample
add header[X-Comment-1] "GNU's Not Unix!"
add [X-Comment-2] "Support FSF!"
@end smallexample
@end deffn

@deffn Command add body @var{text}
Adds the @var{text} to the message body. Use of this command with
@samp{here document} syntax allows to append multi-line text to the
message, e.g.:

@smallexample
@group
add body <<-EOT
    Regards,
    Hostmaster
    EOT
@end group
@end smallexample
@end deffn


@node Removing Headers, Modifying Messages, Adding Headers or Text, Action List
@subsection Removing Headers
@cindex @code{remove}

The command @code{remove} removes the specified header from the
message. The syntax is:

@deffn Command remove [@var{flags}] header @samp{[}@var{string}@samp{]}
@deffnx Command remove [@var{flags}] @samp{[}@var{string}@samp{]}

The name of the header to delete is given by @var{string} parameter.
By default only those headers are removed whose names match it exactly.
Optional @var{flags} allow to change this behavior. @xref{Regular Expressions},
for the detailed description of these.

An example:

@smallexample
remove ["X-Mailer"]
remove :regex ["^X-.*"]
@end smallexample

The first example will remove the @samp{X-Mailer:} header from
an outgoing message, and the second one will remove all "X-*"
headers.
@end deffn


@node Modifying Messages, Inserting Files, Removing Headers, Action List
@subsection Modifying Messages
@cindex @code{modify}

The action command @code{modify} allows to alter the headers
or the body of the message. 

@deffn Command modify [@var{flags}] header @samp{[}@var{key}@samp{]} @samp{[}@var{new-key}@samp{]}
@deffnx Command modify [@var{flags}] @samp{[}@var{key}@samp{]} @samp{[}@var{new-key}@samp{]}

For each header whose name matches @var{key}, replaces its name
with @var{new-key}. If @var{key} is a regular expressions, @var{new-key}
may contain back references. For example, the following statement will
select all headers whose names start with @samp{X-} and change their
names to begin with @samp{X-Old-}:

@smallexample
modify header :re ["X-\(.*\)"] ["X-Old-\1"]
@end smallexample
@end deffn

@deffn Command modify [@var{flags}] header @samp{[}@var{key}@samp{]} @var{value}
@deffnx Command modify [@var{flags}] @samp{[}@var{key}@samp{]} @var{value}

For each header whose name matches @var{key}, changes its value to
@var{value}. For example:

@smallexample
modify [Subject] "New subject"
@end smallexample

@noindent
This statement sets the new value to the @code{Subject} header.

Every occurrence of unescaped @samp{&} in the new value will be replaced
by the old header value. To enter the @samp{&} character itself,
escape it with two backslash characters (@samp{\\}). For example, the
following statement

@smallexample
modify [Subject] "[Anubis \\& others] &"
@end smallexample

@noindent
prepends the @code{Subject} header with the string @samp{[Anubis &
others]}. Thus, the header line

@smallexample
Subject: Test subject
@end smallexample

@noindent

after having been processed by Anubis, will contain:

@smallexample
Subject: [Anubis & others] Test subject
@end smallexample

@end deffn

@deffn Command modify [@var{flags}] header @samp{[}@var{key}@samp{]} @samp{[}@var{new-key}@samp{]} @var{value}
@deffnx Command modify [@var{flags}] @samp{[}@var{key}@samp{]} @samp{[}@var{new-key}@samp{]} @var{value}

Combines the previous two cases, i.e. changes both the header
name and its value, as shown in the following example:

@smallexample
modify header [X-Mailer] [X-X-Mailer] "GNU Anubis"
@end smallexample
@end deffn

@deffn Command modify [@var{flags}] body @samp{[}@var{key}@samp{]}
Removes all occurrences of @var{key} from the message body.
For example, this statement will remove every occurrence of
the word @samp{old}:

@smallexample
modify body ["old"]
@end smallexample
@end deffn

@deffn Command modify [@var{flags}] body @samp{[}@var{key}@samp{]} @var{string}
Replaces all occurrences of @var{key} with @var{string}. For example:

@smallexample
modify body :extended ["the old \([[:alnum:]]+\)"] "the new \1"
@end smallexample
@end deffn


@node Inserting Files, Mail Encryption, Modifying Messages, Action List
@subsection Inserting Files

@deffn Command signature-file-append @var{yes-or-no}
@cmindex signature-file-append @var{yes-or-no}
This action command adds at the end of a message body the
@samp{-- } line, and includes a client's
@file{~/.signature} file. Value @samp{no} is the default.
@end deffn

@deffn Command body-append @var{file-name}
@cmindex body-append @var{file-name}
This action command includes at the end of a message body
the contents of the given file. If @file{@var{file-name}} does
not start with a @samp{/} character, it is taken relative to
the current user home directory
@end deffn

@deffn Command body-clear
@cmindex body-clear
Removes the body of the message
@end deffn

@deffn Command body-clear-append @var{file-name}
@cmindex body-clear-append @var{file-name}
Replaces the message body with the contents of the specified
file. The action is equivalent to the following command sequence:

@smallexample
body-clear
body-append @var{file-name}
@end smallexample
@end deffn


@node Mail Encryption, External Processor, Inserting Files, Action List
@subsection Mail Encryption
@cindex GNU Privacy Guard, GnuPG
@cindex Pretty Good Privacy, PGP
@cindex GPG/PGP private key
@cindex GPG/PGP public key

@deffn Command gpg-passphrase @var{passphrase}
@cmindex gpg-passphrase @var{passphrase}
Specifies your private key's pass phrase for signing an outgoing message
using the GNU Privacy Guard (a tool compatible with the Pretty Good
Privacy). Of course, to protect your passwords in the configuration file use the
0600 (u=rw,g=,o=) permissions, otherwise GNU Anubis won't accept them.
We recommend setting the @samp{gpg-passphrase} once in your
configuration file, e.g. at the start of @code{RULE} section.

GNU Anubis supports the GNU Privacy Guard via the
@dfn{GnuPG Made Easy} library, available at
@w{@uref{http://www.gnupg.org/gpgme.html}}.
@end deffn

@deffn Command gpg-encrypt @var{gpg-keys}
@cmindex gpg-encrypt @var{gpg-keys}
This command enables encrypting your outgoing message with the
GNU Privacy Guard (Pretty Good Privacy) public key(s).
@var{gpg-keys} is a comma separated list of keys (with no space
between commas and keys).

@smallexample
gpg-encrypt "John's public key"
@end smallexample
@end deffn

@deffn Command gpg-sign @var{gpg-signer-key}
@deffnx Command gpg-sign @samp{yes-or-default}
@cmindex gpg-sign @var{gpg-signer-key}
This command signs the outgoing message with your
GNU Privacy Guard private key. Specify a @var{passphrase} with
@code{gpg-passphrase}. Value @samp{default} means your default
private key, but you can change it if you have more than one
private key.

For example:

@smallexample
gpg-sign default
@end smallexample

or

@smallexample
@group
gpg-passphrase "my office key passphrase"
gpg-sign office@@example.key
@end group
@end smallexample
@end deffn

@deffn Command gpg-sign-encrypt @var{gpg-keys}[:@var{gpg-signer-key}]
@deffnx Command gpg-se @var{gpg-keys}[:@var{gpg-signer-key}]
@cmindex gpg-sign-encrypt @var{gpg-keys}[:@var{gpg-signer-key}]
This command simultaneously signs and encrypts your outgoing message.
It has the same effect as @command{gpg} command line switch
@option{-se}. The argument before the colon is a comma-separated list
of PGP keys to encrypt the message with. This argument is mandatory.
The second argument is optional and is separated from the first one
by a colon (@samp{:}). This argument specifies the signer key. In
the absence of the second argument your default private key
is used.

For example:

@smallexample
gpg-sign-encrypt John@@example.key
@end smallexample

or

@smallexample
gpg-se John@@example.key:office@@example.key
@end smallexample
@end deffn


@node External Processor, Quick Example, Mail Encryption, Action List
@subsection Using an External Processor

@deffn Command external-body-processor @var{program} [@var{args}]
@cmindex external-body-processor @var{program} [@var{args}]
Pipes the message body through @var{program}. @var{program} should
be a filter program, that reads the text from the standard input
and prints the transformed text on the standard output. The output
from the @var{program} replaces the body of the message.
@var{args} are any additional arguments the program may require.
@end deffn


@node Quick Example, , External Processor, Action List
@subsection Quick Example

Here is a quick example of using an action list:

@smallexample
@group
---BEGIN RULE---
if header [X-Mailer] :re ".*"
   remove [X-Mailer]
   add [X-Comment] "GNU's Not Unix!"
   gpg-sign "my password"
   signature-file-append yes
fi
---END---
@end group
@end smallexample

@noindent
The example above will remove (on-the-fly) the @samp{X-Mailer:} line from
an outgoing message, add an extra header line (@samp{X-Comment:}), sign your
message with your private key, and add a simple signature file from your
home directory.


@node Using Guile Actions, , Action List, Rule System
@section Using Guile Actions
@cindex Guile

The name Guile stands for @dfn{GNU's Ubiquitous Intelligent Language for
Extensions}. It provides a Scheme interpreter conforming to the R4RS
language specification. GNU Anubis uses Guile as its extension language.

This section describes how to write GNU Anubis actions in Scheme.
It assumes that the reader is sufficiently familiar with the
Scheme language. For information about the language, refer to
@ref{Top,,,r4rs,Revised(4) Report on the Algorithmic Language Scheme}.
For more information about Guile,
@xref{Top,,Overview,guile,The Guile Reference Manual}.

@menu
* Defining Guile Actions::
* Invoking Guile Actions::

Predefined Guile Actions
* Rot-13::
* Remailers::
* Entire Message Filters::
@end menu


@node Defining Guile Actions, Invoking Guile Actions, Using Guile Actions, Using Guile Actions
@subsection Defining Guile Actions
@cindex Guile Actions, defining

A Guile action is defined as follows:

@smalllisp
(define (@var{function-name} @var{header} @var{body} . @var{rest})
 ...)
@end smalllisp

@noindent
Its arguments are:

@table @var
@item header
List of message headers. Each list element is a cons

@smallexample
(@var{name} . @var{value})
@end smallexample

@noindent
where @var{name} is the name of the header field, and @var{value} is
its value with final CRLF stripped off. Both @var{name} and
@var{value} are strings.

@item body
A string containing the message body.

@item rest
Any additional arguments passed to the function from the configuration
file (@pxref{Invoking Guile Actions}). This argument may be absent if
the function is not expected to take optional arguments.
@end table

The function must return a cons whose car contains the new message
headers, and cdr contains the new message body. If the car is
@code{#t}, it means that no headers are changed. If the cdr is
@code{#t}, it means that the body has not changed. If the cdr is
@code{#f}, Anubis will delete the entire message body.

As the first example, let's consider a @dfn{no-operation} action,
i.e. an action that does not alter the message in any way. It can
be written in two ways:

@smalllisp
(define (noop-1 header body)
  (cons header body))
  
(define (noop-2 header body)
  (cons #t #t))
@end smalllisp

The following example is a function that deletes the message body
and adds an additional header:

@smalllisp
(define (proc header body)
  (cons (append header
                (cons "X-Body-Deleted" "yes"))
        #f))
@end smalllisp        

Let's consider a more constructive example. The following function
checks if the @code{Subject} header starts with string @samp{ODP:}
(a Polish equivalent to @samp{Re:}), and if it does, the function
replaces it with @samp{Re:}. It always adds to the message the header

@smallexample
X-Processed-By: GNU Anubis
@end smallexample

@noindent
Additionally, if the optional argument is given, it is appended to
the body of the message.

@smalllisp
(define (fix-subject hdr body . rest)
  "If the Subject: field starts with characters \"ODP:\", replace
them with \"Re:\".
If REST is not empty, append its car to BODY"
  (cons (append
	 (map (lambda (x)
		(if (and (string-ci=? (car x) "subject")
			 (string-ci=? (substring (cdr x) 0 4) "ODP:"))
		    (cons (car x)
			  (string-append "Re:"
					 (substring (cdr x) 4)))
		    x))
	      hdr)
	 (list (cons "X-Processed-By" "GNU Anubis")))
	(if (null? rest)
	    #t
	    (string-append body "\n" (car rest)))))
@end smalllisp


@node Invoking Guile Actions, Rot-13, Defining Guile Actions, Using Guile Actions
@subsection Invoking Guile Actions
@cindex @code{guile-process}

The Guile actions are invoked from the @code{RULE} section using the
@code{guile-process} command. Its syntax is:

@deffn {Scheme Function} @var{function} @var{args}
Arguments:

@table @var
@item function
The name of the Guile function to be invoked.

@item args
Additional arguments. These are passed to the @var{function} as
its third argument (@var{rest}).
@end table
@end deffn

To pass keyword arguments to the function, use the usual Scheme
notation: @samp{#:key}.

As an example, let's consider the invocation of the @code{fix-subject}
function, defined in the previous subsection:

@smallexample
guile-process fix-subject <<-EOT
                                ----------
                                Kind regards,
                                Antonius Block
                          EOT
@end smallexample

@noindent
In this example, the additional argument (a string of three lines) is
passed to the function, which will add it to the message of the body.


@node Rot-13, Remailers, Invoking Guile Actions, Using Guile Actions
@subsection Support for @sc{rot-13}
@cindex rot-13

The @sc{rot-13} transformation is a simple form of encryption where the
letters A-M are transposed with the letters L-Z. It is often used in
Usenet postings/mailing lists to prevent people from accidentally
reading a disturbing message.

GNU Anubis supports @sc{rot}-13 via a loadable Guile function. To enable
this support, you will have to add the following to your @code{GUILE}
section:

@smallexample
guile-load-program rot-13.scm
@end smallexample

Then, in your @code{RULE} section use:

@deffn {Scheme Function} rot-13 @var{keyword-arguments}
@fnindex rot-13, Scheme function
The command accepts the following @var{keyword-arguments}:

@table @code
@item #:body
Encrypt the entire body of the message

@item #:subject
Encrypt the @samp{Subject} header.
@end table

For example:

@smallexample
@group
trigger "rot-13.*body"
 guile-process rot-13 #:body
done

trigger "rot-13.*subj"
 guile-process rot-13 #:subject
done
@end group
@end smallexample  
@end deffn

@node Remailers, Entire Message Filters, Rot-13, Using Guile Actions
@subsection Remailers Type-I
@cindex remailer

GNU Anubis supports remailers of type I. The support is written
entirely in Scheme. To enable it you need to specify the following
in the @code{GUILE} section of your configuration file:

@smallexample
@group
guile-load-program remailer.scm
@end group
@end smallexample

To send the message via a remailer, use the following command
in the @code{RULE} section:

@deffn {Scheme Function} remailer-I @var{keyword-arguments}
@fnindex remailer-I, Scheme function
@cmindex guile-process remailer-I @var{keyword-arguments}
The @var{keyword-arguments} specify the various parameters for
the remailer. These are:

@table @code
@item #:rrt @var{string}
This is the only required keyword argument. It sets the value for the
@dfn{Request Remailing To} line. @var{string} should be your actual
recipient's email address.

@item #:post @var{news-group}
Adds the @samp{Anon-Post-To: @var{news-group}} line,
and prepares the message for sending it to the Usenet
via a remailer. Note, that this is only possible with remailers
that support @samp{Anon-Post-To:} header.

@item #:latent @var{time}
Adds the @samp{Latent-Time:} line, that causes a remailer to keep
your message for specified @var{time} before forwarding it. 

@item #:random
Adds random suffix to the latent time.

@item #:header @var{string}
Adds an extra header line to the remailed message.
@end table

Example:

@smallexample
@group
trigger "remail:(.*)/(.*)"
 guile-process remailer-I \
             #:rrt antonius_block@@helsingor.net \
             #:post \1 \
             #:latent \2 \
             #:header "X-Processed-By: GNU Anubis & Remailer-I"
done
@end group
@end smallexample
@end deffn

Some remailers require the message to be GPG encrypted or signed.
You can achieve this by placing @code{gpg-encrypt} or @code{gpg-sign}
statement right after the invocation of @code{remailer-I}, for
example:

@smallexample
@group
trigger "remail:(.*)/(.*)"
 guile-process remailer-I \
             #:rrt antonius_block@@helsingor.net \
             #:post \1 \
             #:latent \2 \
             #:header "X-Processed-By: GNU Anubis & Remailer-I"
 gpg-sign mykey
done
@end group
@end smallexample

@xref{Mail Encryption}, for more information on mail encryption in
GNU Anubis.

@node Entire Message Filters, , Remailers, Using Guile Actions
@subsection Entire Message Filters
@cindex entire-msg.scm
@fnindex entire-msg-filter, Scheme function
@fnindex openssl-filter, Scheme function
@cindex entire message, filtering

There may be some cases when you need to use an external filter that
processes the entire message (including headers). You cannot use
@code{external-body-processor}, since it feeds only the
message body to the program. To overcome this difficulty, GNU Anubis
is shipped with @file{entire-msg.scm} module. This module provides
Scheme function @code{entire-msg-filter}, which is to be used in
such cases.

@deffn {Scheme Function} entire-msg-filter @var{program} [@var{args}]
Feeds entire message to the given program. The output from the program
replaces message headers and body.

@table @var
@item progname
Full pathname of the program to be executed.

@item args
Any additional arguments it may require.
@end table
@end deffn

Suppose you have a program @code{/usr/libexec/myfilter}, that accepts
entire message as its output and produces on standard output a
modified version of this message. The program takes as its argument
he name of a directory for temporary files. The following example
illustrates how to invoke this program:

@smallexample
BEGIN GUILE
guile-load-program entire-msg.scm
END

SECTION RULE
guile-process entire-msg-filter /usr/libexec/myfilter /tmp
END
@end smallexample

Another function defined in this module is @code{openssl-filter}:

@deffn {Scheme Function} openssl-filter @var{program} [@var{args}]

This function is provided for use with @code{openssl}
program. @code{Openssl} binary attempts to rewind its input and
fails if the latter is a pipe, so @code{openssl} cannot be used
with @code{entire-msg-filter}. Instead, you should use 
@code{openssl-filter}. Its arguments are:

@table @var
@item program
Path to @code{openssl} binary.

@item args
Its arguments
@end table

@xref{S/MIME}, for an example of use of this function.
@end deffn

@node Invoking Anubis, Sample Beginning, Rule System, Top
@chapter Invoking GNU Anubis
@cindex command line

The @command{anubis} executable acts like a daemon.
The behavior of program is controlled by two configuration files,
which have a @strong{higher} priority than command line options.
@xref{Configuration}, for details.

GNU @command{anubis} supports the following command line options:

@table @samp
@item --altrc @var{file}
Specify alternate system configuration file.

@item --bind [@var{host}:]@var{port}
@itemx -b
Specify the TCP port on which GNU Anubis listens for connections.
The default @var{host} value is @w{@samp{INADDR_ANY}}, and default
@var{port} number is 24 (private mail system).

@item --check-config[=@var{level}]
@itemx -c[@var{level}]
Run the configuration file syntax checker. Optional @var{level}
specifies the verbosity level. The following levels are allowed:

@table @asis
@item 0
Display only errors. This is the default.

@item 1
Print the syntax tree after parsing the file.

@item 2
As @samp{1}, but also prints the parser traces.

@item 3
As @samp{2}, but also prints the lexical analyzer traces.
@end table

@item --debug
@itemx -D
Debug mode.

@item --foreground
@itemx -f
Foreground mode.

@item --help
Print short usage summary and exit.

@item --local-mta @var{file}
@itemx -l
Execute a local SMTP server, which works on standard input and output
(inetd-type program). This option excludes the @samp{--remote-mta} option.

@item --mode @var{mode-name}
@itemx -m @var{mode-name}
Selects Anubis operation mode. Allowed values for @var{mode-name}
are @samp{transparent} (default) and @samp{auth}. @xref{Authentication},
for the detailed discussion of Anubis operation modes.

@item --norc
Ignore system configuration file.

@item --relax-perm-check
Do not check a user config file permissions.

@item --remote-mta @var{host}[:@var{port}]
@itemx -r
Specify a remote SMTP host name or IP address, which GNU Anubis will
connect and forward mail to (after a processing).
The default @var{port} number is 25.

@item --silent
@itemx -s
Work silently.

@item --show-config-options
Print a list of configuration options used to build GNU Anubis.

@item --stdio
@itemx -i
Use the SMTP protocol (OMP/Tunnel) as described in RFC 821 on standard
input and output.

@item --verbose
@itemx -v
Work noisily.

@item --version
Print version number and copyright.
@end table

Examples:

@smallexample
$ anubis --remote-mta @var{smtp-host}:25
@end smallexample

@noindent
Run GNU Anubis on port number 24 (private mail system). Note that
you must have root privileges to use port number lower than 1024.
Make the tunnel between your localhost:24 and @var{smtp-host}:25.

@smallexample
$ anubis -f --remote-mta @var{smtp-host}:25
@end smallexample

@noindent
Same as above, but run GNU Anubis in a foreground mode.

@smallexample
$ anubis -f --local-mta /usr/sbin/sendmail -- sendmail -bs
@end smallexample

@noindent
Similar to above, but create a tunnel between localhost:24
and a local program (local MTA). In this example local program
is @command{sendmail} with @samp{-bs} command line option.
The @samp{-bs} option forces @command{sendmail} to work on standard
input and output.

@smallexample
$ anubis --norc --remote-mta @var{smtp-host}:25
@end smallexample

@noindent
Do not read the system configuration file, make the tunnel between
localhost:24 and @var{smtp-host}:25.

@smallexample
$ anubis --bind localhost:1111 --remote-mta @var{smtp-host}:25
@end smallexample

@noindent
Create the tunnel between localhost:1111 and @var{smtp-host}:25.

@smallexample
$ anubis -i
@end smallexample

@noindent
Use the SMTP protocol (OMP/Tunnel) as described in RFC 821
on standard input and output.


@node Sample Beginning, TLS/SSL, Invoking Anubis, Top
@chapter Sample Beginning
@cindex IDENT protocol

By default, GNU Anubis binds to port number 24 (private mail system),
so there shouldn't be any conflict with your local MTA (Mail Transport
Agent). You just have to reconfigure your MUA (Mail User Agent) to make
it talk to GNU Anubis directly on port number 24. All MUAs are normally
set up to talk directly to the MTA, so you must change their settings
and specify GNU Anubis' port number as their target. This makes GNU
Anubis to work as an outgoing mail processor between your MUA and the
MTA. Read your MUA's documentation for more information.

Now you must choose whether you want to connect GNU Anubis with a remote
or local SMTP host via TCP/IP or a local SMTP program, which works on
standard input and output. In the first case, specify the following option:

@smallexample
REMOTE-MTA @var{smtp-host}:25
@end smallexample

@noindent
In the second case (local SMTP program), specify this:

@smallexample
LOCAL-MTA @var{/path/to/your/mta/mta-executable} -bs
@end smallexample

Please note that the @samp{-bs} command line option is a common way
to run MTAs on standard input and output, but it is not a rule.
Read your local MTA's documentation, how to get it working on standard
input and output.

If you would like to run GNU Anubis on port number 25 (which is a default
value for the SMTP) or any other port number, then you must specify the
@samp{bind} keyword. For instance, the following code will bind GNU Anubis
to @samp{localhost:25}:

@smallexample
BIND localhost:25
@end smallexample

This can make a conflict between GNU Anubis and your local MTA, which usually
listens on port number 25. To solve this problem, you can for instance
disable the MTA and specify the @samp{local-mta} keyword, or run MTA on port
number different than GNU Anubis' port number (e.g. 1111). Please read your
local MTA's documentation about this topic. For example:

@smallexample
@group
BIND localhost:25
REMOTE-MTA localhost:1111
@end group
@end smallexample

@strong{Caution:} Make sure that your local machine doesn't accept any
incoming mail (i.e. it is @emph{not} a POP or IMAP server), otherwise
you cannot disable your MTA or change its port number!

@strong{Caution:} It is required to install the TCP/IP IDENT protocol
server (RFC 1413). Without it, an outgoing mail processor will fail.
Most modern GNU/Linux (or *BSD) distributions have already installed
such a server. If not, try @samp{pidentd}, available at:
@w{@uref{ftp://ftp.lysator.liu.se/pub/ident/servers/}}

All Mutt users, who would like to set up GNU Anubis between their MUA
and MTA, should consider using the @samp{msg2smtp.pl} Perl script
from the @file{contrib} directory (part of the distribution).


@node TLS/SSL, S/MIME, Sample Beginning, Top
@chapter Using the TLS/SSL Encryption
@cindex Transport Layer Security, TLS
@cindex Secure Socket Layer, SSL
@cindex GnuTLS
@cindex OpenSSL
@cindex encryption

According to the RFC 2246 document, the TLS (Transport Layer Security)
protocol provides communications privacy over the Internet. The protocol
allows client/server applications to communicate in a way that is designed
to prevent eavesdropping, tampering, or message forgery. The primary goal
of the TLS Protocol is to provide privacy and data integrity between two
communicating applications. The TLS protocol itself is based on the SSL 3.0
(Secure Socket Layer) protocol specification.

GNU Anubis supports the TLS/SSL (via the GnuTLS, a Transport Layer Security
Library available at @w{@uref{http://www.gnutls.org/}}, or OpenSSL,
a cryptographic package available at @w{@uref{http://www.openssl.org/}}),
but your MTA must provide the STARTTLS command first. This can be checked by:

@smallexample
@group
$ telnet @var{your-smtp-host} 25
  ehlo @var{your-domain-name}
@end group
@end smallexample

@noindent
The server will response with all its available commands.
If you see the STARTTLS, then you can use the TLS/SSL encryption.
If your MUA doesn't support the TLS/SSL encryption, but your MTA does,
then you should use the @samp{oneway-ssl} keyword in your configuration
file. Before using the TLS/SSL encryption, you must generate a proper
private key and a certificate. You can do it simply with:

@smallexample
@group
$ cd anubis-directory
$ ./build/keygen.sh
@end group
@end smallexample

@noindent
This will create the @file{anubis.pem} file.
For example copy this file to @w{@file{/usr/share/ssl/certs/}}.
Next, edit your configuration file by adding:

@smallexample
@group
ssl yes
ssl-key @var{path-to-the-private-key}
ssl-cert @var{path-to-the-certificate}
@end group
@end smallexample

For example:

@smallexample
@group
ssl-key /usr/share/ssl/certs/anubis.pem
ssl-cert /usr/share/ssl/certs/anubis.pem
@end group
@end smallexample

@noindent
@strong{Caution:} Each client can specify its own private key
and a certificate by adding the @samp{ssl-key} and @samp{ssl-cert}
keywords in its own user configuration file.

@noindent
@xref{Encryption Settings}, for details.

@node S/MIME, Problems, TLS/SSL, Top
@chapter Using S/MIME Signatures
@cindex smime
@cindex openssl

Anubis version @value{VERSION} does not yet provide built-in support
for S/MIME encryption or signing. To encrypt or sign messages using
S/MIME, you will have to use external programs. Usually such programs
require the whole message as their input, so simply using
@code{external-body-processor} will not work. GNU Anubis distribution
includes a special Guile program, @file{entire-msg.scm}, designed for
use with such programs. For its detailed description, please refer to
@ref{Entire Message Filters}. This chapter addresses a special case of
using it with @code{openssl} to sign outgoing messages.

To use @code{openssl} for S/MIME signing, invoke it using
@code{openssl-filter} function defined in @file{entire-msg.scm}. You
will have to supply at least @code{-sign} and @code{-signer} arguments
to the program. Notice, that you should not specify any input or
output files.

The following example illustrates this approach:

@smallexample
BEGIN GUILE
guile-load-program entire-msg.scm
END

BEGIN RULE
guile-process openssl-filter /usr/local/ssl/bin/openssl \
              smime -sign -signer FILE
END
@end smallexample

@node Problems, Pixie-Dixie, S/MIME, Top
@chapter Reporting Bugs
@cindex bugs
@cindex problems

Please send any bug reports, improvements, comments,
suggestions, or questions to @email{bug-anubis@@gnu.org}.

Before reporting a bug, make sure you have actually found
a real bug. Carefully reread the documentation and see if it
really says you can do what you are trying to do. If it is
not clear whether you should be able to do something or not,
report that too; it's a bug in the documentation!

@node Pixie-Dixie, GNU Free Documentation License, Problems, Top
@chapter Pixie & Dixie
@include pixie-dixie.texi

@node GNU Free Documentation License, Concept Index, Pixie-Dixie, Top
@include fdl.texi


@node Concept Index, , GNU Free Documentation License, Top
@unnumbered Concept Index
@printindex cp
@shortcontents
@contents
@bye

@c anubis.texi ends here
