.\"
.\" anubis.1 --
.\"
.TH anubis 1 "" "" "GNU Anubis"
.SH NAME
GNU Anubis -- an SMTP message submission daemon.
.SH SYNOPSIS
.BI "anubis"
[options]
.br

.SH DESCRIPTION
.B GNU Anubis
is an SMTP message submission daemon. It represents an intermediate layer
between mail user agent (MUA) and mail transport agent (MTA), receiving
messages from the MUA, applying to them a set of predefined changes and
finally inserting modified messages into an MTA routing network. The set
of changes applied to a message is configurable on a system-wide and
per-user basis. The built-in configuration language used for defining
sets of changes allows for considerable flexibility and is easily extensible.

.SH THE GNU ANUBIS MANUAL

The full documentation for
.B GNU Anubis
is maintained as a Texinfo manual.  If the
.B info
and GNU Anubis programs are properly installed at your site,
the command
.IP
.B info anubis
.PP
should give you access to the complete manual.

.SH REPORTING BUGS

Please send any bug reports, improvements, comments,
suggestions, or questions to <bug-anubis@gnu.org>.

Before reporting a bug, make sure you have actually found
a real bug. Carefully reread the documentation and see if it
really says you can do what you are trying to do. If it is
not clear whether you should be able to do something or not,
report that too; it's a bug in the documentation!

.SH FILES
.HP
.I /etc/anubisrc
- system configuration file
.HP
.I ~/.anubisrc
- user configuration file

.SH "SEE ALSO"

.BR grep (1),
.BR regex (7),
.BR perlre (1),
.BR pcre (3),
.BR sendmail (8),
.BR openssl (1),
.BR gpg (1),
.BR identd (1),
.BR pam (8),
.BR tcpd (8)

.SH AUTHORS

The Anubis Team (read the AUTHORS file).
.P
.PD 0
GNU Anubis Home Page:
.P
http://www.gnu.org/software/anubis/
.PD

.SH LICENSE

GNU Anubis is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.
.P
GNU Anubis is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.P
You should have received a copy of the GNU General Public License along
with GNU Anubis.  If not, see <http://www.gnu.org/licenses/>.

